### ISSUE TITLE
Illegal instruction error on Linux

### ISSUE THREAD

**Issue by foggynight** [drcode/zek#1]
Hello Conrad,

I'm getting an illegal instruction error when executing the `zek_linux` binary on Arch Linux x86_64. Inspecting with `gdb` output the following:

```
Program received signal SIGILL, Illegal instruction.
0x000000000028daef in memset ()
```

Building from source using `zig build` worked perfectly though.

Robert Coffey

**Comment by drcode** [comment]
Hmmm... so `zek_linux` seems to work OK for me, I guess there must be variations between different linuxes on executable format. I renamed the file to `zek_debian` to make this clearer.

**Comment by kristoff-it** [comment]
I think I can provide a precise answer to this question and give a happy resolution :^)

What I suspect is happening is that @drcode is creating the release for Linux by compiling for his own machine (by not specifying a target option) and then distributing that executable. When Zig is not given a target platform it produces an optimized build that uses all the features that the native CPU supports. My bet is that through this mechanism, memset got optimized into a vectorized operation using an AVX instruction or similar.

The problem with doing so is that the resulting executable is unfortunately less portable as some x86_64 CPUs don't have those instructions, causing the application to crash.

To produce a more portable version of the executable @drcode needs to pass a target option also when building for linux, as it will select a baseline CPU model. I believe `zig build -Dtarget=x86_64-linux` will suffice and, since it's going to produce a statically linked executable, I'm confident it will work for all reasonable Linuxes out there (and also for most of the less reasonable ones).

**Comment by drcode** [comment]
I think @kristoff-it has the right diagnosis. I updated the Linux build to his recommendations. Hopefully will work on other Linuxes now.
